FROM dunglas/frankenphp:php8.5-alpine

WORKDIR /app

RUN install-php-extensions \
    pdo_pgsql \
    pgsql \
    intl \
    zip \
    bcmath \
    gd \
    mbstring \
    opcache

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

EXPOSE 8000

CMD ["frankenphp", "php-server", "-r", "public/", "--listen", "0.0.0.0:8000"]